insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Liqueur Banana, Ramazzotti', 78.08);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Muffin Batt - Carrot Spice', 89.94);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Jackson Triggs Okonagan', 76.11);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Sprouts - Brussel', 73.45);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Garlic - Primerba, Paste', 24.59);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Soup Campbells', 54.36);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese - St. Andre', 31.79);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Roll, Whole Wheat', 28.14);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Coffee Cup 12oz 5342cd', 93.63);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Flour - Whole Wheat', 48.23);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Beef - Roasted, Cooked', 50.88);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Octopus', 6.23);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Pineapple, 48 Oz', 82.85);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Inside', 86.73);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Beef - Rouladin, Sliced', 46.27);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Monkfish Fresh - Skin Off', 15.87);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Delicato Merlot', 88.2);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Cherries - Frozen', 71.29);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Lamb Rack - Ontario', 87.13);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Sugar - Splenda Sweetener', 96.07);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Amarula Cream', 15.09);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Chicken Breast Wing On', 32.67);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Whmis Spray Bottle Graduated', 94.47);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Beef - Striploin Aa', 3.09);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Beaujolais Villages', 47.62);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Tea - Black Currant', 12.31);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Rabbit - Legs', 32.43);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Jolt Cola - Electric Blue', 44.3);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Capon - Breast, Wing On', 46.37);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Muffin Mix - Morning Glory', 95.33);
